version: "3.9"
services:
 flask_test_app:
   container_name: flask_product_service_app
   image: product_service/flask_api:1.0
   build: .
   ports:
     - "4000:4000"
   environment:
     - DB_URL=${DB_URL}

   depends_on:
   - flask_product_db

 flask_product_db:
   container_name: flask_product_db
   image: postgres:12
   ports:
     - "5431:5432"
   environment:
     # - POSTGRES_PASSWORD=postgres_pass_example
     # - POSTGRES_USER=postgres_user_example
     # - POSTGRES_DB=postgres_example
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
   volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}